apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myns

resources:
- ../base
- ns.yaml
- service.yaml
- deploy.yaml
- ingress.yaml

commonAnnotations:
  sample-go/version: v1
