apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tams-dev

resources:
- ../../base
- ns.yaml

patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: sample-go-tams-dev.tuf.local
  target:
    group: networking.k8s.io
    kind: Ingress
    name: sample-go-ingress
    version: v1

commonAnnotations:
  sample-go/version: v2
