apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: sample-go
  name: sample-go-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: sample-go.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-go
            port:
              number: 8080
