apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: aws-elasticsearch-output
spec:
  opensearch:
    host: 192.168.1.247
    index_name: "logs"
    user: "admin"
    password: 
      value: "admin"
    ssl_verify: false  
    buffer:
      timekey: 1m
      timekey_wait: 10s
      timekey_use_utc: true