apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: aws-elasticsearch-output
spec:
  opensearch:
    host: 192.168.1.247
    port: 9200
    scheme: https
    ssl_verify: false
    logstash_format: true
    include_timestamp: true
    user: admin
    password:
      value: "admin"
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true      